# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    secrets:
      GDRIVE_CLIENT_ID:
        required: true
      GDRIVE_CLIENT_SECRET:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Using secret"
        env:
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}